postsubmits:

  bartoszmajsak-test/template-golang:
    - name: patchset-updater
      decorate: true
      decoration_config:
        skip_cloning: true
      always_run: true
      optional: false
      skip_submodules: true
      branches:
        - ^release-.*$
      spec:
        containers:
          - image: "quay.io/bmajsak/prow-create-patches:latest"
            imagePullPolicy: Always
            env:
              # TODO: take from secrets
              - name: "GITHUB_TOKEN"
                value: "ASDF" #
              - name: "GIT_USER"
                value: "bartoszmajsak-test"
              - name: "GIT_EMAIL"
                value: "bartoszmajsak+test@gmail.com"
            command: ["create-patches"]
            args:
            - "--repo=github.com/bartoszmajsak-test/template-golang"
            - "--patchset=github.com/bartoszmajsak-test/patchset"
            - "--main=master"
            - "--dev=release-2.1" ## TODO how to get the branch name?
            ## TODO after updating patchset run verification?
  
    - name: patchset-verifier
      decorate: true
      decoration_config:
        skip_cloning: true
      always_run: true
      optional: false
      skip_submodules: true
      branches:
        - ^master$
      spec:
        containers:
          - image: "quay.io/bmajsak/prow-check-conflicts:latest"
            imagePullPolicy: Always
            env:
              # TODO: take from secrets
              - name: "GITHUB_TOKEN"
                value: "ASDF" #
              - name: "GIT_USER"
                value: "bartoszmajsak-test"
              - name: "GIT_EMAIL"
                value: "bartoszmajsak+test@gmail.com"
            command: ["check-conflicts"]
            args:
            - "--repo=github.com/bartoszmajsak-test/template-golang"
            - "--patchset=github.com/bartoszmajsak-test/patchset"
            - "--main=master"
            - "--dev=release-2.1" ## TODO how to get the branch name?
