presubmits:

  bartoszmajsak-test/template-golang:
    - name: patch-fix-validation
      trigger: "(?m)^/resolved"
      rerun_command: "/resolved"
      decorate: true
      always_run: false
      optional: false
      spec:
        containers:
          - image: "quay.io/bmajsak/prow-validate-resolution:latest"
            imagePullPolicy: Always
            env:
              # TODO: take from secrets
              - name: "GITHUB_TOKEN"
                value: "ASDF"
              - name: "GIT_USER"
                value: "bartoszmajsak-test"
              - name: "GIT_EMAIL"
                value: "bartoszmajsak+test@gmail.com"
            command: ["validate-resolution"]
            args:
              - "--repo=github.com/bartoszmajsak-test/template-golang"
              - "--patchset=github.com/bartoszmajsak-test/patchset"
              - "--main=master"